# https://github.com/googleapis/repo-automation-bots/tree/main/packages/sync-repo-settings
# Rules for main branch protection
branchProtectionRules:
# Identifies the protection rule pattern. Name of the branch to be protected.
# Defaults to `main`
- pattern: master
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: true
  requiredStatusCheckContexts:
    - '.NET/integration-tests-on-emulator.yml'
    - '.NET/integration-tests-on-production.yml'
    - '.NET/build-and-test.yml'
    - 'cla/google'
