// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using Google.Cloud.Spanner.Admin.Database.V1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Google.Cloud.EntityFrameworkCore.Spanner.Extensions;
using Xunit;

namespace Google.Cloud.EntityFrameworkCore.Spanner.Tests.MigrationTests
{
    /// <summary>
    /// Tests migrations using an in-mem Spanner mock server.
    /// </summary>
    [CollectionDefinition(nameof(MigrationMockServerTests), DisableParallelization = true)]
    [Collection(nameof(MigrationMockServerTests))]
    public class MigrationMockServerTests : IClassFixture<SpannerMockServerFixture>
    {
        private readonly SpannerMockServerFixture _fixture;

        public MigrationMockServerTests(SpannerMockServerFixture service)
        {
            _fixture = service;
            service.SpannerMock.Reset();
            service.DatabaseAdminMock.Reset();
        }

        private string ConnectionString => $"Data Source=projects/p1/instances/i1/databases/d1;Host={_fixture.Host};Port={_fixture.Port}";

        [Fact]
        public void TestMigrateUsesDdlBatch()
        {
            var version = typeof(Migration).Assembly.GetName().Version ?? new Version();
            var formattedVersion = $"{version.Major}.{version.Minor}.{version.Build}";
            _fixture.SpannerMock.AddOrUpdateStatementResult("SELECT 1", StatementResult.CreateException(MockSpannerService.CreateDatabaseNotFoundException("d1")));
            _fixture.SpannerMock.AddOrUpdateStatementResult(
                $"INSERT INTO `EFMigrationsHistory` (`MigrationId`, `ProductVersion`){Environment.NewLine}VALUES ('''20210309110233_Initial''', '''{formattedVersion}''')",
                StatementResult.CreateUpdateCount(1)
            );
            _fixture.SpannerMock.AddOrUpdateStatementResult(
                $"INSERT INTO `EFMigrationsHistory` (`MigrationId`, `ProductVersion`){Environment.NewLine}VALUES ('''20210830_V2''', '''{formattedVersion}''')",
                StatementResult.CreateUpdateCount(1)
            );
            using var db = new MockMigrationSampleDbContext(ConnectionString);
            db.Database.Migrate();
            
            Assert.Collection(_fixture.DatabaseAdminMock.Requests,
                // The initial request will create an empty database and then create the migrations history table.
                request => Assert.IsType<CreateDatabaseRequest>(request),
                request =>
                {
                    var update = request as UpdateDatabaseDdlRequest;
                    Assert.NotNull(update);
                    Assert.Collection(update.Statements,
                        sql => Assert.StartsWith("CREATE TABLE `EFMigrationsHistory`", sql)
                    );
                },
                // Each migration will be executed as a separate DDL batch.
                request =>
                {
                    var update = request as UpdateDatabaseDdlRequest;
                    Assert.NotNull(update);
                    Assert.Collection(update.Statements,
                        sql => Assert.StartsWith("CREATE TABLE `Singers`", sql),
                        sql => Assert.StartsWith("CREATE SEQUENCE `MySequence` OPTIONS (sequence_kind=bit_reversed_positive, start_with_counter=100", sql),
                        sql => Assert.StartsWith("CREATE TABLE `TableWithAllColumnTypes`", sql),
                        sql => Assert.StartsWith("CREATE TABLE `Venues`", sql),
                        sql => Assert.StartsWith("CREATE TABLE `Albums`", sql),
                        sql => Assert.StartsWith("CREATE TABLE `Concerts`", sql),
                        sql => Assert.StartsWith("CREATE TABLE `Tracks`", sql),
                        sql => Assert.StartsWith("CREATE TABLE `Performances`", sql),
                        sql => Assert.StartsWith($"CREATE TABLE `TicketSales` ({Environment.NewLine}    `Id` INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE),{Environment.NewLine}", sql),
                        sql => Assert.StartsWith("CREATE INDEX `AlbumsByAlbumTitle2`", sql),
                        sql => Assert.StartsWith("CREATE INDEX `Idx_Singers_FullName`", sql),
                        sql => Assert.StartsWith("CREATE NULL_FILTERED INDEX `IDX_TableWithAllColumnTypes_ColDate_ColCommitTS`", sql),
                        sql => Assert.StartsWith("CREATE UNIQUE INDEX `Idx_Tracks_AlbumId_Title`", sql)
                    );
                },
                request =>
                {
                    var update = request as UpdateDatabaseDdlRequest;
                    Assert.NotNull(update);
                    Assert.Collection(update.Statements,
                        sql => Assert.StartsWith(" DROP INDEX `IDX_TableWithAllColumnTypes_ColDate_ColCommitTS`", sql),
                        sql => Assert.StartsWith("DROP TABLE `TableWithAllColumnTypes`", sql),
                        sql => Assert.StartsWith($"CREATE TABLE `OtherSequenceKind` ({Environment.NewLine}    `Id` INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (NON_EXISTING_KIND),{Environment.NewLine}", sql),
                        sql => Assert.StartsWith($"CREATE TABLE `NoSequenceKind` ({Environment.NewLine}    `Id` INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY,{Environment.NewLine}", sql),
                        sql => Assert.StartsWith($"CREATE TABLE `GenerationStrategyAlways` ({Environment.NewLine}    `Id` INT64 NOT NULL GENERATED ALWAYS AS IDENTITY (BIT_REVERSED_POSITIVE),{Environment.NewLine}", sql),
                        sql => Assert.StartsWith($"CREATE TABLE `AutoIncrement` ({Environment.NewLine}    `Id` INT64 NOT NULL AUTO_INCREMENT,{Environment.NewLine}", sql)
                    );
                }
            );
        }

        [Fact]
        public async Task TestStartMigrateAsync()
        {
            var version = typeof(Migration).Assembly.GetName().Version ?? new Version();
            var formattedVersion = $"{version.Major}.{version.Minor}.{version.Build}";
            _fixture.SpannerMock.AddOrUpdateStatementResult("SELECT 1", StatementResult.CreateSelect1ResultSet());
            _fixture.SpannerMock.AddOrUpdateStatementResult(
                "SELECT EXISTS(SELECT 1 FROM information_schema.tables WHERE table_catalog = '' and table_schema = '' and table_name = '''EFMigrationsHistory''')",
                StatementResult.CreateSelectTrueResultSet());
            _fixture.SpannerMock.AddOrUpdateStatementResult($"SELECT `MigrationId`, `ProductVersion`{Environment.NewLine}" +
                                                            $"FROM `EFMigrationsHistory`{Environment.NewLine}" +
                                                            $"ORDER BY `MigrationId`",
                StatementResult.CreateResultSet(new List<Tuple<Cloud.Spanner.V1.TypeCode, string>>
                    {
                        Tuple.Create(Cloud.Spanner.V1.TypeCode.String, "MigrationId"),
                        Tuple.Create(Cloud.Spanner.V1.TypeCode.String, "ProductVersion"),
                    },
                    new List<object[]>
                    {
                        new object[] { "20210309110233_Initial", formattedVersion },
                    }));
            _fixture.SpannerMock.AddOrUpdateStatementResult(
                $"INSERT INTO `EFMigrationsHistory` (`MigrationId`, `ProductVersion`){Environment.NewLine}VALUES ('''20210830_V2''', '''{formattedVersion}''')",
                StatementResult.CreateUpdateCount(1)
            );
            await using var db = new MockMigrationSampleDbContext(ConnectionString);
            // This starts an asynchronous database migration, but does not wait for the DDL operation to finish.
            await db.Database.StartMigrateAsync();
            
            Assert.Collection(_fixture.DatabaseAdminMock.Requests,
                // Each migration will be executed as a separate DDL batch.
                request =>
                {
                    var update = request as UpdateDatabaseDdlRequest;
                    Assert.NotNull(update);
                    Assert.Collection(update.Statements,
                        sql => Assert.StartsWith(" DROP INDEX `IDX_TableWithAllColumnTypes_ColDate_ColCommitTS`", sql),
                        sql => Assert.StartsWith("DROP TABLE `TableWithAllColumnTypes`", sql),
                        sql => Assert.StartsWith($"CREATE TABLE `OtherSequenceKind` ({Environment.NewLine}    `Id` INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (NON_EXISTING_KIND),{Environment.NewLine}", sql),
                        sql => Assert.StartsWith($"CREATE TABLE `NoSequenceKind` ({Environment.NewLine}    `Id` INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY,{Environment.NewLine}", sql),
                        sql => Assert.StartsWith($"CREATE TABLE `GenerationStrategyAlways` ({Environment.NewLine}    `Id` INT64 NOT NULL GENERATED ALWAYS AS IDENTITY (BIT_REVERSED_POSITIVE),{Environment.NewLine}", sql),
                        sql => Assert.StartsWith($"CREATE TABLE `AutoIncrement` ({Environment.NewLine}    `Id` INT64 NOT NULL AUTO_INCREMENT,{Environment.NewLine}", sql)
                    );
                }
            );
        }

        [Fact]
        public async Task TestStartDdlAsync()
        {
            await using var db = new MockMigrationSampleDbContext(ConnectionString);
            await db.Database.StartDdlAsync([
                "create table my_table (id int64 primary key, value string(max))",
                "create index my_index on my_table (value)",
            ]);
            
            Assert.Collection(_fixture.DatabaseAdminMock.Requests,
                request =>
                {
                    var update = request as UpdateDatabaseDdlRequest;
                    Assert.NotNull(update);
                    Assert.Collection(update.Statements,
                        sql => Assert.Equal("create table my_table (id int64 primary key, value string(max))", sql),
                        sql => Assert.Equal("create index my_index on my_table (value)", sql)
                    );
                }
            );
        }
    }
}
