// Copyright 2021 Google Inc. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// <auto-generated />
using Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests.TableSplittingTests;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests.TableSplittingTests.Migrations
{
    [DbContext(typeof(TestTableSplittingDbContext))]
    [Migration("20210224080116_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests.TableSplittingTests.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT64");

                    b.Property<string>("Status")
                        .HasColumnName("Status")
                        .HasColumnType("STRING");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests.TableSplittingTests.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INT64");

                    b.Property<string>("BillingAddress")
                        .HasColumnType("STRING");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("STRING");

                    b.Property<string>("Status")
                        .HasColumnName("Status")
                        .HasColumnType("STRING");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests.TableSplittingTests.Models.OrderDetail", b =>
                {
                    b.HasOne("Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests.TableSplittingTests.Models.Order", null)
                        .WithOne("OrderDetail")
                        .HasForeignKey("Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests.TableSplittingTests.Models.OrderDetail", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
