// <auto-generated />
using Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests.TableSplittingTests;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests.TableSplittingTests.Migrations
{
    [DbContext(typeof(TestTableSplittingDbContext))]
    [Migration("20210224080116_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests.TableSplittingTests.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT64");

                    b.Property<string>("Status")
                        .HasColumnName("Status")
                        .HasColumnType("STRING");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests.TableSplittingTests.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INT64");

                    b.Property<string>("BillingAddress")
                        .HasColumnType("STRING");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("STRING");

                    b.Property<string>("Status")
                        .HasColumnName("Status")
                        .HasColumnType("STRING");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests.TableSplittingTests.Models.OrderDetail", b =>
                {
                    b.HasOne("Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests.TableSplittingTests.Models.Order", null)
                        .WithOne("OrderDetail")
                        .HasForeignKey("Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests.TableSplittingTests.Models.OrderDetail", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
