on:
  push:
    branches: [ main ]
  pull_request:
permissions:
  contents: read
  pull-requests: write
name: ADO.NET Tests
jobs:
  units:
    strategy:
      matrix:
        dotnet-version: ['8.0.x', '9.0.x']
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install dotnet
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: '1.26.x'
      - name: Checkout go-sql-spanner
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: 'googleapis/go-sql-spanner'
          path: spanner-ado-net/spanner-ado-net/go-sql-spanner
          persist-credentials: false
      - name: Build SpannerLib binaries
        run: ./build-binaries.sh true
        working-directory: spanner-ado-net/spanner-ado-net
        shell: bash
      - name: spanner-ado-net-tests
        working-directory: spanner-ado-net/spanner-ado-net-tests
        run: dotnet test --filter "Category!=Integration" --verbosity normal
        shell: bash
      - name: spanner-ado-net-specification-tests
        working-directory: spanner-ado-net/spanner-ado-net-specification-tests
        run: dotnet test --verbosity normal
        shell: bash
      - name: spanner-ado-net-sample-tests
        working-directory: spanner-ado-net/spanner-ado-net-samples-tests
        run: dotnet test --verbosity normal
        shell: bash
        if: matrix.os != 'ubuntu-24.04-arm'
      - name: dotnet run sample
        working-directory: spanner-ado-net/spanner-ado-net-samples
        run: dotnet run HelloWorld
        shell: bash
        # Docker is only supported on Linux on GitHub Actions
        if: runner.os == 'Linux' && matrix.os != 'ubuntu-24.04-arm'

  integration-tests:
    runs-on: ubuntu-latest
    services:
      emulator:
        image: gcr.io/cloud-spanner-emulator/emulator:1.5.55
        ports:
          - 9010:9010
          - 9020:9020
    strategy:
      matrix:
        dotnet-version: ['8.0.x', '9.0.x']
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install dotnet
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: '1.26.x'
      - name: Checkout go-sql-spanner
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: 'googleapis/go-sql-spanner'
          path: spanner-ado-net/spanner-ado-net/go-sql-spanner
          persist-credentials: false
      - name: Build SpannerLib binaries
        run: ./build-binaries.sh true
        working-directory: spanner-ado-net/spanner-ado-net
        shell: bash
      - name: Run Schema Integration Tests
        working-directory: spanner-ado-net/spanner-ado-net-tests
        run: dotnet test --filter "Category=Integration" --verbosity normal
        shell: bash
