name: integration-tests-on-production

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-env:
    outputs:
      has-key: ${{ steps.project-id.outputs.defined }}
    runs-on: ubuntu-latest
    steps:
    - id: project-id
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      if: "${{ env.GCP_PROJECT_ID != '' }}"
      run: echo "::set-output name=defined::true"

  integration-tests-on-prod:
    needs: [check-env]
    if: needs.check-env.outputs.has-key == 'true'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: Setup .NET
      uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
      with:
        dotnet-version: 10.0.x
    - id: 'auth'
      uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093' # v3.0.0
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: Setup GCloud
      uses: google-github-actions/setup-gcloud@26f734c2779b00b7dda794207734c511110a4368 # v3.0.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Integration Tests on Production
      working-directory: ./Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests
      run: dotnet test --verbosity normal
      env:
        JOB_TYPE: test
        TEST_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
