name: Sync SpannerLib .NET code from go-sql-spanner

on:
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Checkout go-sql-spanner
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: 'googleapis/go-sql-spanner'
          path: spanner-ado-net/spanner-ado-net/go-sql-spanner
          persist-credentials: false

      - name: Copy SpannerLib code
        run: ./copy-spannerlib-source.sh true
        working-directory: spanner-ado-net/spanner-ado-net
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: sync SpannerLib code"
          branch: automated-spanner-lib-code-update
          title: "chore: sync SpannerLib code"
          body: "Update the ADO.NET driver with the latest SpannerLib code."
          base: main
          committer: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
